# Alternative way to create secrets using YAML
# This shows you how secrets look as Kubernetes manifests

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret-yaml
  namespace: ca2-learning
type: Opaque
data:
  # Values must be base64 encoded
  # echo -n 'admin' | base64 = YWRtaW4=
  # echo -n 'supersecret123' | base64 = c3VwZXJzZWNyZXQxMjM=
  # echo -n 'plant_monitoring' | base64 = cGxhbnRfbW9uaXRvcmluZw==
  root-username: YWRtaW4=
  root-password: c3VwZXJzZWNyZXQxMjM=
  database: cGxhbnRfbW9uaXRvcmluZw==

---
# You can also use stringData for unencoded values (Kubernetes will encode them)
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret-stringdata
  namespace: ca2-learning
type: Opaque
stringData:  # No base64 encoding needed with stringData
  root-username: admin
  root-password: supersecret123
  database: plant_monitoring