# Free Tier Optimized Application Manifests

## **Resource-Constrained MongoDB Configuration**

```yaml
# mongodb-freetier.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-micro
  namespace: plant-monitoring
spec:
  serviceName: mongodb-micro-headless
  replicas: 1  # Single instance only
  selector:
    matchLabels:
      app: mongodb-micro
  template:
    metadata:
      labels:
        app: mongodb-micro
    spec:
      containers:
      - name: mongodb
        image: mongo:6.0.4
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password123"
        # CRITICAL: Reduced resource requirements
        resources:
          requests:
            memory: "128Mi"    # Minimum for MongoDB
            cpu: "100m"        # 0.1 CPU core
          limits:
            memory: "256Mi"    # Max 256MB RAM
            cpu: "200m"        # Max 0.2 CPU core
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        # MongoDB optimization for low memory
        command:
        - mongod
        - --wiredTigerCacheSizeGB
        - "0.1"              # Use only 100MB cache
        - --smallfiles       # Use smaller data files
        - --nojournal        # Disable journaling (data loss risk!)
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gp2  # Use gp2 for free tier
      resources:
        requests:
          storage: 5Gi       # Small storage footprint

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-micro-service
  namespace: plant-monitoring
spec:
  selector:
    app: mongodb-micro
  ports:
  - port: 27017
    targetPort: 27017
```

## **Lightweight Kafka Configuration**

```yaml
# kafka-freetier.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-micro
  namespace: plant-monitoring
spec:
  serviceName: kafka-micro-headless
  replicas: 1  # Single broker only
  selector:
    matchLabels:
      app: kafka-micro
  template:
    metadata:
      labels:
        app: kafka-micro
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.4.0
        ports:
        - containerPort: 9092
        env:
        # Single-node Kafka configuration (KRaft mode)
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@kafka-micro-0:9093"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092,CONTROLLER://:9093"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-micro-0:9092"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        # CRITICAL: Low memory JVM settings
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx128M -Xms128M"  # Only 128MB heap
        - name: KAFKA_JVM_PERFORMANCE_OPTS
          value: "-XX:+UseG1GC -XX:MaxGCPauseMillis=20"
        resources:
          requests:
            memory: "200Mi"    # Minimum for Kafka
            cpu: "100m"        
          limits:
            memory: "300Mi"    # Max 300MB RAM
            cpu: "200m"        
        volumeMounts:
        - name: kafka-data
          mountPath: /var/lib/kafka/data
  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: gp2
      resources:
        requests:
          storage: 5Gi

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-micro-service
  namespace: plant-monitoring
spec:
  selector:
    app: kafka-micro
  ports:
  - port: 9092
    targetPort: 9092
```

## **Ultra-Lightweight Data Processor**

```yaml
# processor-freetier.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plant-processor-micro
  namespace: plant-monitoring
spec:
  replicas: 1  # Single instance
  selector:
    matchLabels:
      app: plant-processor-micro
  template:
    metadata:
      labels:
        app: plant-processor-micro
    spec:
      containers:
      - name: processor
        image: alpine:latest  # Minimal base image
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo 'Processing sensor data...'; sleep 30; done"]
        env:
        - name: MONGODB_URI
          value: "mongodb://admin:password123@mongodb-micro-service:27017"
        - name: KAFKA_BROKERS
          value: "kafka-micro-service:9092"
        resources:
          requests:
            memory: "32Mi"     # Tiny memory footprint
            cpu: "25m"         # 0.025 CPU core
          limits:
            memory: "64Mi"     # Max 64MB RAM
            cpu: "50m"         # Max 0.05 CPU core
```

## **Resource Monitoring Dashboard**

```yaml
# resource-monitor.yaml
apiVersion: v1
kind: Pod
metadata:
  name: resource-monitor
  namespace: plant-monitoring
spec:
  containers:
  - name: monitor
    image: alpine:latest
    command: ["/bin/sh"]
    args:
    - -c
    - |
      apk add --no-cache curl
      while true; do
        echo "=== Resource Usage at $(date) ==="
        echo "Memory usage:"
        cat /proc/meminfo | grep -E "(MemTotal|MemFree|MemAvailable)"
        echo "CPU usage:"
        cat /proc/loadavg
        echo "Disk usage:"
        df -h /
        echo "=========================="
        sleep 60
      done
    resources:
      requests:
        memory: "16Mi"
        cpu: "10m"
      limits:
        memory: "32Mi"
        cpu: "20m"
```

## **Free Tier Deployment Strategy**

### **Phase 1: Deploy Core Services**
```bash
# Apply minimal resource configurations
kubectl apply -f mongodb-freetier.yaml
kubectl apply -f kafka-freetier.yaml

# Wait for pods to be ready (may take longer on t2.micro)
kubectl wait --for=condition=ready pod -l app=mongodb-micro --timeout=300s
kubectl wait --for=condition=ready pod -l app=kafka-micro --timeout=300s
```

### **Phase 2: Test Resource Constraints**
```bash
# Monitor resource usage
kubectl apply -f resource-monitor.yaml
kubectl logs -f resource-monitor

# Test basic functionality
kubectl exec -it mongodb-micro-0 -- mongosh --eval "db.adminCommand('ping')"
kubectl exec -it kafka-micro-0 -- kafka-topics --create --topic test --bootstrap-server localhost:9092
```

### **Phase 3: Gradual Service Addition**
```bash
# Add services one at a time, monitoring resources
kubectl apply -f processor-freetier.yaml

# If memory becomes constrained, scale down or remove components
kubectl scale statefulset mongodb-micro --replicas=0  # Temporary shutdown
```

## **Troubleshooting Free Tier Issues**

### **Out of Memory (OOM) Kills**
```bash
# Check for OOMKilled pods
kubectl get pods --field-selector=status.phase=Failed

# Reduce resource limits further
kubectl patch statefulset kafka-micro -p='{"spec":{"template":{"spec":{"containers":[{"name":"kafka","resources":{"limits":{"memory":"200Mi"}}}]}}}}'
```

### **CPU Throttling**
```bash
# Monitor CPU throttling
kubectl top nodes
kubectl top pods

# Reduce CPU requests if needed
kubectl patch deployment plant-processor-micro -p='{"spec":{"template":{"spec":{"containers":[{"name":"processor","resources":{"requests":{"cpu":"10m"}}}]}}}}'
```

### **Storage Optimization**
```bash
# Use smaller PVC sizes
kubectl patch pvc kafka-data-kafka-micro-0 -p='{"spec":{"resources":{"requests":{"storage":"2Gi"}}}}'

# Clean up unused volumes
kubectl delete pvc --all -n plant-monitoring
```

## **Success Metrics for Free Tier**

- ✅ All pods running without OOMKills
- ✅ Basic Kafka topic creation and messaging
- ✅ MongoDB connection and simple queries  
- ✅ System resource usage <80% of t2.micro limits
- ✅ Learning objectives achieved despite constraints

**Remember**: This setup prioritizes **learning and cost optimization** over production readiness. Perfect for educational purposes!