---
# Secure Secrets Management for Kubernetes Plant Monitoring System
# This playbook creates Kubernetes secrets with randomly generated passwords
# NO HARDCODED PASSWORDS!

- name: Create Kubernetes Secrets for Plant Monitoring System
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
    - name: Ensure namespace exists
      kubernetes.core.k8s:
        name: "{{ namespace }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: Generate secure random passwords
      set_fact:
        mongodb_root_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=24') }}"
        mongodb_app_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=24') }}"
        homeassistant_admin_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"
        mqtt_password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits length=16') }}"
      no_log: true

    - name: Create MongoDB credentials secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ mongodb_secret_name }}"
            namespace: "{{ namespace }}"
            labels:
              app: mongodb
              component: database
          type: Opaque
          data:
            root-username: "{{ 'admin' | b64encode }}"
            root-password: "{{ mongodb_root_password | b64encode }}"
            app-username: "{{ 'plantuser' | b64encode }}"
            app-password: "{{ mongodb_app_password | b64encode }}"
            database-name: "{{ 'plant_monitoring' | b64encode }}"
            connection-string: "{{ ('mongodb://plantuser:' + mongodb_app_password + '@mongodb-service:27017/plant_monitoring') | b64encode }}"
      no_log: true

    - name: Create Home Assistant credentials secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ homeassistant_secret_name }}"
            namespace: "{{ namespace }}"
            labels:
              app: homeassistant
              component: dashboard
          type: Opaque
          data:
            admin-username: "{{ 'admin' | b64encode }}"
            admin-password: "{{ homeassistant_admin_password | b64encode }}"
            secret-key: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,punctuation length=32') | b64encode }}"
      no_log: true

    - name: Create MQTT credentials secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ mqtt_secret_name }}"
            namespace: "{{ namespace }}"
            labels:
              app: mqtt
              component: messaging
          type: Opaque
          data:
            username: "{{ 'mqttuser' | b64encode }}"
            password: "{{ mqtt_password | b64encode }}"
      no_log: true

    - name: Create application configuration ConfigMap
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: app-config
            namespace: "{{ namespace }}"
            labels:
              app: plant-monitoring
              component: config
          data:
            KAFKA_BROKERS: "kafka-service:9092"
            KAFKA_TOPIC: "{{ sensor_data_topic }}"
            MQTT_BROKER: "homeassistant-service"
            MQTT_PORT: "1883"
            MQTT_DISCOVERY_PREFIX: "{{ mqtt_discovery_prefix }}"
            PLANT_STATUS_TOPIC: "{{ plant_status_topic }}"
            SENSOR_DATA_TOPIC: "{{ sensor_data_topic }}"
            TIMEZONE: "{{ homeassistant_timezone }}"

    - name: Create Home Assistant configuration ConfigMap
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: homeassistant-config
            namespace: "{{ namespace }}"
            labels:
              app: homeassistant
              component: dashboard
          data:
            TZ: "{{ homeassistant_timezone }}"
            LATITUDE: "{{ homeassistant_latitude | string }}"
            LONGITUDE: "{{ homeassistant_longitude | string }}"
            ELEVATION: "{{ homeassistant_elevation | string }}"

    - name: Create plant sensor configuration ConfigMap
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: plant-sensor-config
            namespace: "{{ namespace }}"
            labels:
              app: plant-sensor
              component: sensors
          data:
            SENSOR_INTERVAL: "30"
            KAFKA_TOPIC: "{{ sensor_data_topic }}"

    - name: Create Kafka configuration ConfigMap
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: kafka-config
            namespace: "{{ namespace }}"
            labels:
              app: kafka
              component: messaging
          data:
            KAFKA_BROKERS: "kafka-service:9092"

    - name: Display setup completion message
      debug:
        msg:
          - "✅ Kubernetes secrets and config created successfully"
          - "🔐 All passwords are randomly generated and stored securely"
          - "📝 Secrets created:"
          - "   - {{ mongodb_secret_name }}"
          - "   - {{ homeassistant_secret_name }}"
          - "   - {{ mqtt_secret_name }}"
          - "📋 ConfigMaps created for application configuration"
          - "🚀 Ready for application deployment"

    - name: Save credentials for debugging (REMOVE IN PRODUCTION)
      copy:
        content: |
          # GENERATED CREDENTIALS - FOR DEVELOPMENT ONLY
          # DELETE THIS FILE IN PRODUCTION!
          
          MongoDB Root: admin / {{ mongodb_root_password }}
          MongoDB App: plantuser / {{ mongodb_app_password }}
          Home Assistant: admin / {{ homeassistant_admin_password }}
          MQTT: mqttuser / {{ mqtt_password }}
        dest: "/tmp/plant-monitoring-credentials.txt"
        mode: '0600'
      no_log: false
      when: ansible_check_mode is not defined

    - name: Security reminder
      debug:
        msg:
          - "🛡️  SECURITY REMINDER:"
          - "   - Credentials are stored in Kubernetes secrets"
          - "   - Temporary file created at /tmp/plant-monitoring-credentials.txt"
          - "   - DELETE the temp file after testing!"
          - "   - In production, integrate with external secret management"