apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
  namespace: plant-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi