# RBAC (Role-Based Access Control) for Plant Monitoring System
# Implements least-privilege access following Kubernetes security best practices

---
# Service Account for Plant Processor
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plant-processor-sa
  namespace: plant-monitoring
  labels:
    app: plant-processor
    component: processing

---
# Service Account for Plant Sensors  
apiVersion: v1
kind: ServiceAccount
metadata:
  name: plant-sensor-sa
  namespace: plant-monitoring
  labels:
    app: plant-sensor
    component: sensors

---
# Service Account for Home Assistant
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homeassistant-sa
  namespace: plant-monitoring
  labels:
    app: homeassistant
    component: dashboard

---
# Role for Plant Processor - Limited ConfigMap and Secret access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: plant-monitoring
  name: plant-processor-role
rules:
# Allow reading ConfigMaps for application configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Allow reading Secrets for database credentials
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
# Allow creating events for monitoring
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
# Role for Plant Sensors - Minimal read access only
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: plant-monitoring
  name: plant-sensor-role
rules:
# Allow reading ConfigMaps for sensor configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Allow creating events for monitoring
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
# Role for Home Assistant - Dashboard access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: plant-monitoring
  name: homeassistant-role
rules:
# Allow reading ConfigMaps
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Allow reading Secrets for MQTT and database access
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
# Allow creating events
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
# RoleBinding for Plant Processor
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: plant-processor-binding
  namespace: plant-monitoring
subjects:
- kind: ServiceAccount
  name: plant-processor-sa
  namespace: plant-monitoring
roleRef:
  kind: Role
  name: plant-processor-role
  apiGroup: rbac.authorization.k8s.io

---
# RoleBinding for Plant Sensors
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: plant-sensor-binding
  namespace: plant-monitoring
subjects:
- kind: ServiceAccount
  name: plant-sensor-sa
  namespace: plant-monitoring
roleRef:
  kind: Role
  name: plant-sensor-role  
  apiGroup: rbac.authorization.k8s.io

---
# RoleBinding for Home Assistant
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: homeassistant-binding
  namespace: plant-monitoring
subjects:
- kind: ServiceAccount
  name: homeassistant-sa
  namespace: plant-monitoring
roleRef:
  kind: Role
  name: homeassistant-role
  apiGroup: rbac.authorization.k8s.io

# Note: PodSecurityPolicy was deprecated and removed in Kubernetes 1.25+
# Pod security is now enforced through Pod Security Standards at the namespace level
# and individual pod securityContext configurations