# Pod Security Standards and Security Contexts
# Implements defense-in-depth security following CIS Kubernetes Benchmark

---
# Security Context Template for Plant Monitoring Applications
# Apply these security contexts to all application deployments

# Example security context for applications (use in deployment templates):
# securityContext:
#   runAsNonRoot: true
#   runAsUser: 1000
#   runAsGroup: 3000
#   fsGroup: 2000
#   seccompProfile:
#     type: RuntimeDefault
#   capabilities:
#     drop:
#     - ALL
#   allowPrivilegeEscalation: false
#   readOnlyRootFilesystem: true

---
# Network Security - Additional security headers for HTTPS
apiVersion: v1
kind: ConfigMap
metadata:
  name: security-config
  namespace: plant-monitoring
data:
  # TLS Configuration
  tls.conf: |
    # Minimum TLS version
    ssl_protocols TLSv1.2 TLSv1.3;
    
    # Strong cipher suites
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    
    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;
    
  # Content Security Policy
  csp-policy: |
    default-src 'self';
    script-src 'self' 'unsafe-inline' 'unsafe-eval';
    style-src 'self' 'unsafe-inline';
    img-src 'self' data: https:;
    connect-src 'self' ws: wss:;
    font-src 'self';
    object-src 'none';
    media-src 'self';
    form-action 'self';
